framework:
    messenger:
        transports:
            async_registration_mail:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    exchange:
                        type: direct
                        name: registration_mail
                    queues:
                        registration_mail: ~

