services:
  php-fpm:
    build: docker
    container_name: 'online_store_php'
    ports:
      - '9010:9000'
    volumes:
      - ./:/app
    working_dir: /app
    networks:
      - online_store

  nginx:
    image: nginx
    container_name: 'online_store_nginx'
    working_dir: /app
    ports:
      - '8888:80'
    volumes:
      - ./:/app
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - online_store

  postgres:
    image: postgres:15
    ports:
      - 15432:5432
    container_name: 'online_store_db'
    working_dir: /app
    restart: always
    environment:
      POSTGRES_DB: 'online_store'
      POSTGRES_USER: 'dbuser'
      POSTGRES_PASSWORD: 'dbpwd'
    volumes:
      - dump:/app/dump
      - postgresql:/var/lib/postgresql/data
    networks:
      - online_store

  redis:
    image: redis:7.0.0
    ports:
      - 6379:6379
    networks:
      - online_store

  rabbitmq:
    image: rabbitmq:3.10.7-management
    ports:
      - 5672:5672
    environment:
      - RABBITMQ_DEFAULT_USER=rmuser
      - RABBITMQ_DEFAULT_PASS=rmpassword
    networks:
      - online_store

networks:
  online_store:
    driver: bridge

volumes:
  dump:
  postgresql:
