product_controllers:
    resource:
        path: ../src/Product/Controller/
        namespace: App\Product\Controller
    type: attribute

category_controllers:
    resource:
        path: ../src/Category/Controller/
        namespace: App\Category\Controller
    type: attribute

user_controllers:
    resource:
        path: ../src/User/Controller/
        namespace: App\User\Controller
    type: attribute

